<?php
/**
 * Example deployment secret file — copy to smartucf-key.php when building production ZIP.
 *
 * Do NOT commit smartucf-key.php to Git. Merchants do not edit this file.
 *
 * @package MTUC
 */

defined( 'ABSPATH' ) || exit;

return array(
	'smartucf_key_password' => '',
);
